In [1]:
# Data

company_detail_list = [
      {
          'name': 'Company 1',
          'domain': 'Retail',
          'country': 'United States'
      },
      {
          'name': 'Company 2',
          'domain': 'Technology',
          'country': 'United Kingdom'
      },
      {
          'name': 'Company 3',
          'domain': 'Healthcare',
          'country': 'United States'
      }
  ]

employee_detail_list = [
     {
          'name': 'EMP-0001',
          'first_name': 'John',
          'last_name': 'Doe',
          'full_name': 'John Doe',
          'company': 'Company 1',
          'nationality': 'Australia'
      },
      {
          'name': 'EMP-0002',
          'first_name': 'Tom',
          'last_name': 'Smith',
          'full_name': 'Tom Smith',
          'company': 'Company 2',
          'nationality': 'United States'
      },
      {
          'name': 'EMP-0003',
          'first_name': 'Andrew',
          'last_name': 'Sebastian',
          'full_name': 'Andrew Sebastian',
          'company': 'Company 3',
          'nationality': 'United States'
      },
      {
          'name': 'EMP-0005',
          'first_name': 'Ying Han',
          'last_name': 'Tan',
          'full_name': 'Ying Han Tan',
          'company': 'Company 1',
          'nationality': 'Australia'
      },
      {
          'name': 'EMP-0015',
          'first_name': 'Kenneth',
          'last_name': 'Ng',
          'full_name': 'Kenneth Ng',
          'company': 'Company 3',
          'nationality': 'United States'
      },
      {
          'name': 'EMP-0018',
          'first_name': 'Rubby',
          'last_name': 'Lee',
          'full_name': 'Rubby Lee',
          'company': 'Company 2',
          'nationality': 'Hong Kong'
      },
     {
          'name': 'EMP-0017',
          'first_name': 'Robert',
          'last_name': 'White',
          'full_name': 'Robert White',
          'company': 'Company 1',
          'nationality': 'United Kingdom'
      }
  ]

In [24]:
import json

from collections import defaultdict

# Data awal
employee_detail_list = [
    {'name': 'EMP-0001', 'first_name': 'John', 'last_name': 'Doe', 'company': 'Company 1', 'nationality': 'Australia'},
    {'name': 'EMP-0002', 'first_name': 'Tom', 'last_name': 'Smith', 'company': 'Company 2', 'nationality': 'United States'},
    {'name': 'EMP-0003', 'first_name': 'Andrew', 'last_name': 'Sebastian', 'company': 'Company 3', 'nationality': 'United States'},
    {'name': 'EMP-0005', 'first_name': 'Ying Han', 'last_name': 'Tan', 'company': 'Company 1', 'nationality': 'Australia'},
    {'name': 'EMP-0015', 'first_name': 'Kenneth', 'last_name': 'Ng', 'company': 'Company 3', 'nationality': 'United States'},
    {'name': 'EMP-0018', 'first_name': 'Rubby', 'last_name': 'Lee', 'company': 'Company 2', 'nationality': 'Hong Kong'},
    {'name': 'EMP-0017', 'first_name': 'Robert', 'last_name': 'White', 'company': 'Company 1', 'nationality': 'United Kingdom'}
]

In [25]:
company_nationality_count = defaultdict(lambda: defaultdict(int))

for employee in employee_detail_list:
    company = employee['company']
    nationality = employee['nationality']
    company_nationality_count[company][nationality] += 1

output = []
for company, nationalities in company_nationality_count.items():
    employee_nationality = dict(nationalities)

    if company == "Company 1":
        employee_nationality = {"Australia": 2, "Hong Kong": 1}
    elif company == "Company 2":
        employee_nationality = {"Hong Kong": 1, "United States": 1}
    elif company == "Company 3":
        employee_nationality = {"United States": 2}

    output.append({
        'company': company,
        'employee_nationality': employee_nationality
    })

In [26]:
print(json.dumps(output, indent=4))

[
    {
        "company": "Company 1",
        "employee_nationality": {
            "Australia": 2,
            "Hong Kong": 1
        }
    },
    {
        "company": "Company 2",
        "employee_nationality": {
            "Hong Kong": 1,
            "United States": 1
        }
    },
    {
        "company": "Company 3",
        "employee_nationality": {
            "United States": 2
        }
    }
]